-- ============================================================
-- DESE TOUR OPERATIONS CENTER
-- ROLLBACK: V10 (tour auto-provisioning) -> V9
-- ============================================================
-- File:    supabase_migration_civitatis_write_v10_ROLLBACK_to_v9.sql
--
-- WHAT THIS FILE IS
-- ─────────────────────────────────────────────────────────────
-- A safety rollback, prepared for review ONLY — NOT executed, and not
-- intended to be executed unless V10
-- (supabase_migration_civitatis_write_v10_tour_auto_provisioning.sql)
-- has already been applied and needs to be undone. It drops the V10
-- 26-parameter public.ingest_civitatis_booking(...) signature and
-- recreates the function EXACTLY as
-- supabase_migration_civitatis_write_v9_diagnostic_stage_instrumentation.sql
-- defines it — the CREATE FUNCTION body below is copied verbatim from
-- that file, not retyped or reconstructed from memory, specifically to
-- eliminate any risk of transcription drift between "V9 as documented"
-- and "V9 as this rollback actually restores." The COMMENT ON FUNCTION
-- and REVOKE/GRANT statements are likewise copied verbatim from that
-- same file.
--
-- WHAT THIS FILE DOES NOT DO
-- ─────────────────────────────────────────────────────────────
-- This is a function-definition rollback ONLY. It contains no DELETE,
-- no UPDATE, no TRUNCATE, and no ALTER TABLE of any kind — it cannot
-- touch a single row in reservations, customers, tours, tour_channels,
-- tour_languages, or email_ingestions. Any tour V10 auto-provisioned
-- before this rollback runs, any reservation it created, any customer
-- it resolved or created — all of it remains exactly as committed.
-- Dropping and recreating a function's DEFINITION never touches the
-- data any call to that function already wrote; only a FUTURE call
-- (which would now run V9's logic, with no auto-provisioning capability
-- at all — a booking that needed provisioning would once again reach
-- Step 2's up-front p_tour_id check and become needs_review, exactly as
-- pre-V10 behavior) is affected.
--
-- WHY THIS IS SAFE TO REVIEW INDEPENDENTLY OF V10 ITSELF
-- ─────────────────────────────────────────────────────────────
-- This file's own correctness does not depend on which specific defect
-- (if any) V10 turned out to have — it restores a KNOWN, previously-
-- reviewed, already-live-or-about-to-be-live function definition
-- byte-for-byte. A reviewer can verify this file is correct by
-- confirming the CREATE FUNCTION body below is IDENTICAL to the one in
-- supabase_migration_civitatis_write_v9_diagnostic_stage_instrumentation.sql
-- (it is — this file was generated by direct extraction from that file,
-- not hand-written).
--
-- HOW TO APPLY (once reviewed and approved — NOT done as part of
-- producing this file; only run this if a rollback from V10 is actually
-- needed)
-- ─────────────────────────────────────────────────────────────
-- Supabase Dashboard → SQL Editor → paste and run this file. Wrapped in
-- an explicit BEGIN/COMMIT so it either fully applies or not at all.
-- Idempotent: safe to re-run (DROP FUNCTION IF EXISTS on an
-- already-dropped signature is a no-op; CREATE OR REPLACE and
-- REVOKE/GRANT are idempotent by construction, same as every migration
-- in this series).
-- ============================================================


BEGIN;

-- ──────────────────────────────────────────────────────────────────────────
-- Drop the V10 (26-parameter) signature explicitly — CREATE OR REPLACE
-- alone cannot safely restore the V9 (23-parameter) signature when the
-- parameter list itself is changing back down; see V10's own "SCOPE OF
-- THIS MIGRATION" section for the identical reasoning in the forward
-- direction.
-- ──────────────────────────────────────────────────────────────────────────

DROP FUNCTION IF EXISTS public.ingest_civitatis_booking(
  TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TEXT, UUID, TEXT, DATE, TIME,
  INTEGER, INTEGER, NUMERIC, TEXT, NUMERIC, TEXT, UUID, TEXT, TEXT, TEXT, JSONB,
  BOOLEAN, TEXT, TEXT
);


-- ──────────────────────────────────────────────────────────────────────────
-- FUNCTION: ingest_civitatis_booking — restored to V9, verbatim from
-- supabase_migration_civitatis_write_v9_diagnostic_stage_instrumentation.sql
-- ──────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.ingest_civitatis_booking(
  p_gmail_message_id    TEXT,
  p_gmail_thread_id     TEXT,
  p_received_at         TIMESTAMPTZ,
  p_raw_subject         TEXT,
  p_raw_body_snapshot   TEXT,
  p_event_type          TEXT,        -- 'new_booking' | 'modified' — anything else is needs_review
  p_source_id           UUID,
  p_external_booking_id TEXT,
  p_tour_id             UUID,        -- already resolved by matching.js's matchTourChannel (exact match only)
  p_tour_language       TEXT,
  p_check_in            DATE,
  p_check_in_time       TIME,
  p_pax_adult           INTEGER,
  p_pax_child           INTEGER,     -- the ONE field allowed to default (to 0) — see V3 changelog point 2
  p_total_amount        NUMERIC,     -- Civitatis Net price -> reservations.total_amount
  p_currency            TEXT,
  p_retail_amount       NUMERIC,     -- Civitatis Retail price -> reservations.retail_amount
  p_retail_currency     TEXT,
  p_customer_id         UUID,        -- pre-resolved by matching.js's matchCustomer; NULL means "create" (CREATE path only — see V3 changelog point 4)
  p_customer_full_name  TEXT,        -- used ONLY on the CREATE path when p_customer_id IS NULL
  p_customer_email      TEXT,        -- used ONLY on the CREATE path when p_customer_id IS NULL
  p_customer_phone      TEXT,        -- used ONLY on the CREATE path when p_customer_id IS NULL
  p_passengers          JSONB        -- [{"fullName":"...", "sortOrder":0}, ...] from api/civitatis/parser.js
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ingestion_id        UUID;
  v_existing_status      TEXT;
  v_existing_res_id       UUID;
  v_missing_fields         TEXT[] := '{}';
  v_customer_id              UUID;
  v_reservation_id             UUID;
  v_reservation_number          TEXT;
  v_tour_name                    TEXT;
  v_result                        TEXT;
  v_newer_exists                    BOOLEAN;
  v_expected_passenger_count          INTEGER;
  v_usable_passenger_count              INTEGER;
  v_passengers_replaced                   BOOLEAN := FALSE;
  v_error_text                              TEXT;
  -- V9: diagnostic-only. v_stage records the last stage entered before
  -- Step 3 onward; the six v_diag_* variables are populated ONLY inside
  -- the EXCEPTION handler, from GET STACKED DIAGNOSTICS — see V9
  -- CHANGELOG above. None of these are ever persisted outside this one
  -- function call except inside error_reason/the returned JSONB, in
  -- exactly the same way v_error_text/SQLERRM always already were.
  v_stage                                     TEXT;
  v_diag_sqlstate                              TEXT;
  v_diag_constraint                             TEXT;
  v_diag_table                                   TEXT;
  v_diag_column                                   TEXT;
  v_diag_detail                                    TEXT;
  v_diag_hint                                       TEXT;
  v_diag_context                                     TEXT;
BEGIN
  -- ── Step 0 (V6): non-blocking, gmail_message_id-scoped processing lock
  -- — acquired BEFORE Step 1 is even attempted, and BEFORE the row is
  -- touched in any way. Closes the exact race an external review found
  -- in V5: without this, two concurrent retries of the SAME 'failed' row
  -- could both reach business processing if the first one's own retry
  -- failed again (see V6 changelog point 10, and the *** CORRECTED BY V6
  -- CHANGELOG POINT 10 *** note in the V5 changelog above, for the full
  -- interleaving V5 missed). Namespaced with a distinct string prefix AND
  -- a different seed (1) than the existing Step 3 booking-level lock
  -- (source_id:external_booking_id, seed 0) — the two locks are
  -- independent and Step 3's lock is completely unchanged.
  IF NOT pg_try_advisory_xact_lock(
    hashtextextended('civitatis_ingest:gmail_message:' || p_gmail_message_id, 1)
  ) THEN
    -- Another transaction currently owns processing for this EXACT
    -- Gmail message (a fresh first-ever insert, or a failed-row retry
    -- claim, both from Step 1 below) — never wait for it to finish and
    -- re-decide against its outcome (that is precisely what V5 got
    -- wrong). Report the LAST COMMITTED state instead: this SELECT
    -- cannot and does not see the current lock holder's own uncommitted
    -- work (ordinary READ COMMITTED visibility), so it may under-report
    -- (e.g. still show 'failed' while the holder is, right now,
    -- successfully retrying it) — that is intentional and safe, since
    -- this branch's only job is "refuse to act," never to describe the
    -- holder's live progress. No row visible at all (NULL) means the
    -- current holder is itself mid-way through a first-ever insert for
    -- this message, not yet committed — reported as 'received', which is
    -- exactly what that situation is. Reuses the existing
    -- result:"already_processed" vocabulary; no new RPC result value.
    SELECT id, processing_status, reservation_id
      INTO v_ingestion_id, v_existing_status, v_existing_res_id
      FROM public.email_ingestions
     WHERE gmail_message_id = p_gmail_message_id;
    RETURN jsonb_build_object(
      'result', 'already_processed',
      'ingestion_id', v_ingestion_id,
      'processing_status', COALESCE(v_existing_status, 'received'),
      'reservation_id', v_existing_res_id
    );
  END IF;

  -- ── Step 1 (unchanged from V5): Gmail-message-level idempotency, WITH
  -- safe retry for a PREVIOUSLY-FAILED attempt at the SAME message ──────
  -- Atomic at the database level via a single conditional UPSERT, not an
  -- application-side "SELECT then UPDATE". Records the event_type LABEL
  -- as given (even if invalid — COALESCEd to 'unknown' only for this
  -- audit row) so there is always a permanent record of what was
  -- received; validity is enforced in Step 2 BEFORE any business write.
  -- Concurrent execution of THIS statement for the SAME gmail_message_id
  -- is now impossible by construction — the Step 0 lock above guarantees
  -- only one transaction at a time ever reaches here for a given
  -- message — so, unlike in V5, this UPSERT no longer needs to (and
  -- does not) defend against a second, concurrently-blocked evaluator.
  --
  -- Three possible outcomes of this single statement:
  --   (a) no existing row for this gmail_message_id -> plain INSERT
  --       succeeds, RETURNING gives the new id -> fresh attempt.
  --   (b) existing row's processing_status = 'failed' -> the ON CONFLICT
  --       DO UPDATE's WHERE clause matches -> the SAME row is atomically
  --       reclaimed (flipped to 'received', stale failure metadata
  --       cleared), RETURNING gives the SAME id -> retry attempt,
  --       Step 2 onward proceeds exactly as for a fresh attempt.
  --   (c) existing row's processing_status IN
  --       ('processed','received','needs_review') -> the WHERE clause
  --       does not match -> zero rows are inserted or updated ->
  --       RETURNING gives no row -> v_ingestion_id stays NULL -> falls
  --       through to the already_processed report below, exactly as V4.
  INSERT INTO public.email_ingestions (
    gmail_message_id, gmail_thread_id, external_booking_id, source_id,
    event_type, processing_status, raw_subject, raw_body_snapshot, received_at
  ) VALUES (
    p_gmail_message_id, p_gmail_thread_id, p_external_booking_id, p_source_id,
    CASE WHEN p_event_type IN ('new_booking', 'modified') THEN p_event_type ELSE 'unknown' END,
    'received', p_raw_subject, p_raw_body_snapshot,
    COALESCE(p_received_at, NOW())
  )
  ON CONFLICT (gmail_message_id) DO UPDATE
    SET processing_status = 'received',
        error_reason      = NULL,
        processed_at      = NULL
    -- Deliberately NOT reset on a retry: gmail_thread_id, external_booking_id,
    -- source_id, event_type, raw_subject, raw_body_snapshot, received_at —
    -- a retry is the SAME Gmail message, not a new one; its original
    -- identity and raw audit content are preserved unless a concrete
    -- reason to refresh them arises (none does here).
    WHERE public.email_ingestions.processing_status = 'failed'
  RETURNING id INTO v_ingestion_id;

  IF v_ingestion_id IS NULL THEN
    -- Outcome (c) above: an existing row that is 'processed', 'received',
    -- or 'needs_review'. All three are terminal for THIS (automatic)
    -- call path — 'needs_review' in particular is intentionally never
    -- auto-retried (see V5 changelog point 9); its processing_status is
    -- still reported here so a caller/operator can see it needs a
    -- SEPARATE, explicit/manual review mechanism (out of scope for this
    -- function) rather than assuming it is simply done.
    SELECT id, processing_status, reservation_id
      INTO v_ingestion_id, v_existing_status, v_existing_res_id
      FROM public.email_ingestions
     WHERE gmail_message_id = p_gmail_message_id;
    RETURN jsonb_build_object(
      'result', 'already_processed',
      'ingestion_id', v_ingestion_id,
      'processing_status', v_existing_status,
      'reservation_id', v_existing_res_id
    );
  END IF;

  -- ── Step 2: consolidated required-field validation — BEFORE any
  -- customer/reservation/guest/activity write is even attempted. Every
  -- field checked here is guaranteed non-null by api/civitatis/parser.js
  -- for any event with ok:true (see that file's reasons.push(...) calls
  -- for internalCode/languageRaw/date/time/adultCount/retail/net/client);
  -- a NULL here on a real ingestion call means either the caller
  -- (writeAdapter.js) has a bug or the underlying data is genuinely
  -- unusable — either way, this function never substitutes a fabricated
  -- value (see V3 changelog point 2). p_pax_child is deliberately NOT
  -- validated here: parser.js/dryRun.js's own established contract is
  -- that an absent child count means zero children, not missing data.
  IF p_source_id IS NULL THEN
    v_missing_fields := array_append(v_missing_fields, 'source_id');
  END IF;
  IF p_external_booking_id IS NULL OR btrim(p_external_booking_id) = '' THEN
    v_missing_fields := array_append(v_missing_fields, 'external_booking_id');
  END IF;
  IF p_tour_id IS NULL THEN
    v_missing_fields := array_append(v_missing_fields, 'tour_id (Internal code did not match tour_channels)');
  END IF;
  IF p_event_type IS NULL OR p_event_type NOT IN ('new_booking', 'modified') THEN
    v_missing_fields := array_append(v_missing_fields, 'event_type (must be exactly new_booking or modified)');
  END IF;
  IF p_check_in IS NULL THEN
    v_missing_fields := array_append(v_missing_fields, 'check_in');
  END IF;
  IF p_check_in_time IS NULL THEN
    v_missing_fields := array_append(v_missing_fields, 'check_in_time');
  END IF;
  IF p_pax_adult IS NULL OR p_pax_adult <= 0 THEN
    v_missing_fields := array_append(v_missing_fields, 'pax_adult');
  END IF;
  IF p_total_amount IS NULL THEN
    v_missing_fields := array_append(v_missing_fields, 'total_amount (Civitatis Net price)');
  END IF;
  IF p_currency IS NULL OR btrim(p_currency) = '' THEN
    v_missing_fields := array_append(v_missing_fields, 'currency');
  END IF;
  IF p_retail_amount IS NULL THEN
    v_missing_fields := array_append(v_missing_fields, 'retail_amount (Civitatis Retail price)');
  END IF;
  IF p_retail_currency IS NULL OR btrim(p_retail_currency) = '' THEN
    v_missing_fields := array_append(v_missing_fields, 'retail_currency');
  END IF;
  IF p_tour_language IS NULL OR btrim(p_tour_language) = '' THEN
    v_missing_fields := array_append(v_missing_fields, 'tour_language');
  END IF;
  -- ── V8: p_passengers, when provided, must be a genuine JSONB ARRAY —
  -- never a JSONB scalar (string/number/boolean) or a JSONB object.
  -- NULL remains explicitly allowed here (see V8 changelog point 12 and
  -- the migration header "WHY THIS MIGRATION EXISTS" for the full
  -- incident this check exists to prevent from ever reaching Step 2b's
  -- jsonb_array_elements call as an unhandled exception again).
  -- jsonb_typeof() never raises for any well-formed, non-NULL JSONB
  -- value — this check itself cannot introduce a new failure mode.
  IF p_passengers IS NOT NULL AND jsonb_typeof(p_passengers) <> 'array' THEN
    v_missing_fields := array_append(v_missing_fields, 'passengers (must be a JSON array when provided)');
  END IF;

  IF array_length(v_missing_fields, 1) > 0 THEN
    UPDATE public.email_ingestions
       SET processing_status = 'needs_review',
           error_reason = 'missing required field(s): ' || array_to_string(v_missing_fields, ', '),
           processed_at = NOW()
     WHERE id = v_ingestion_id;
    RETURN jsonb_build_object(
      'result', 'manual_review_required',
      'ingestion_id', v_ingestion_id,
      'reason', 'missing required field(s)',
      'missing_fields', to_jsonb(v_missing_fields)
    );
  END IF;

  -- ── Step 2b (V7): passenger-completeness inputs, computed ONCE here
  -- and reused by both the CREATE and MODIFICATION branches in Step 6
  -- below. Pure computation over already-validated scalar inputs
  -- (p_pax_adult is already confirmed NOT NULL/>0 by Step 2 above) and
  -- p_passengers — neither expression can itself raise, so it is safe
  -- to compute unconditionally here, before the nested transactional
  -- block, exactly like v_missing_fields above. usable_passenger_count
  -- uses the EXACT SAME rule the reservation_guests INSERT statements
  -- further below use to decide what actually gets persisted (non-null,
  -- non-blank after btrim) — never just JSON array length, so a blank-
  -- name entry can never masquerade as a real passenger here, and
  -- legitimate duplicate names are never deduplicated (COUNT(*), not
  -- COUNT(DISTINCT fullName)).
  v_expected_passenger_count := p_pax_adult + COALESCE(p_pax_child, 0);
  SELECT COUNT(*) INTO v_usable_passenger_count
    FROM jsonb_array_elements(COALESCE(p_passengers, '[]'::jsonb)) AS g
   WHERE btrim(g->>'fullName') IS NOT NULL AND btrim(g->>'fullName') <> '';

  BEGIN  -- nested block: on any unexpected error below, roll back every
         -- customer/reservation/guest/activity write attempted in this
         -- call (but NOT the email_ingestions row from Step 1, which
         -- this handler explicitly re-records as 'failed' after the
         -- implicit rollback-to-savepoint) — see migration header.
    v_stage := 'nested_block_entry';  -- V9: diagnostic only

    -- ── Step 3: serialize concurrent processing of the SAME booking ──────
    -- hashtextextended returns bigint, matching pg_advisory_xact_lock's
    -- signature; released automatically at transaction end (COMMIT or
    -- ROLLBACK) — never needs an explicit unlock call. Acquired BEFORE
    -- the reservation lookup it protects.
    v_stage := 'booking_advisory_lock';  -- V9: diagnostic only
    PERFORM pg_advisory_xact_lock(
      hashtextextended(p_source_id::text || ':' || p_external_booking_id, 0)
    );

    -- ── Step 4: locate the existing reservation for this booking, if any
    -- — moved BEFORE any customer write (V3 changelog points 1 and 4).
    -- FOR UPDATE locks the row (if found) for the remainder of this
    -- transaction, consistent with the advisory lock's serialization.
    v_stage := 'reservation_lookup';  -- V9: diagnostic only
    SELECT id, customer_id INTO v_reservation_id, v_customer_id
      FROM public.reservations
     WHERE source_id = p_source_id AND external_booking_id = p_external_booking_id
     FOR UPDATE;

    -- ── Step 5: ordering guard — has a NEWER event for this booking
    -- already been applied? Only meaningful when a reservation already
    -- exists; a booking with no reservation yet cannot have a 'processed'
    -- email_ingestions row either (Step 8 always sets both together), so
    -- this is trivially FALSE when v_reservation_id IS NULL.
    v_stage := 'newer_event_check';  -- V9: diagnostic only
    SELECT EXISTS (
      SELECT 1 FROM public.email_ingestions
       WHERE source_id = p_source_id
         AND external_booking_id = p_external_booking_id
         AND processing_status = 'processed'
         AND received_at > COALESCE(p_received_at, NOW())
    ) INTO v_newer_exists;

    -- ── Step 6: branch — fully explicit, exhaustive event/reservation-
    -- state matrix (V4 changelog point 8). Every branch condition names
    -- BOTH p_event_type and the reservation-existence state explicitly
    -- — a reservation UPDATE is reachable ONLY via the one branch that
    -- requires p_event_type = 'modified' AND an existing reservation
    -- AND NOT v_newer_exists, all three, together. A 'new_booking'
    -- event can NEVER reach the UPDATE branch, regardless of
    -- received_at ordering — see the explicit
    -- "booking_already_exists" branch below, which handles a second,
    -- genuinely distinct 'new_booking' Gmail message for a booking that
    -- already has a reservation.
    --
    --   event_type=new_booking, no reservation          -> CREATE
    --   event_type=modified,    reservation exists,
    --                            not stale                -> UPDATE
    --   event_type=modified,    reservation exists,
    --                            stale                     -> stale_ignored
    --   event_type=modified,    no reservation              -> manual_review_required
    --   event_type=new_booking, reservation exists            -> booking_already_exists
    IF v_reservation_id IS NOT NULL AND p_event_type = 'new_booking' THEN
      -- A second, distinct Gmail message that Civitatis itself
      -- classified as "New booking A########:" (not a modification) for
      -- a booking that already has a reservation. This is NOT a
      -- modification and must never be treated as one — zero business-
      -- state side effects beyond this event's own audit row: no
      -- customer created or changed, no reservation field changed, no
      -- passenger replaced, no activity created (V4 changelog point 8).
      v_stage := 'booking_already_exists_mark';  -- V9: diagnostic only
      UPDATE public.email_ingestions
         SET processing_status = 'processed', reservation_id = v_reservation_id, processed_at = NOW()
       WHERE id = v_ingestion_id;
      RETURN jsonb_build_object(
        'result', 'booking_already_exists',
        'ingestion_id', v_ingestion_id,
        'reservation_id', v_reservation_id,
        'customer_id', v_customer_id
      );

    ELSIF v_reservation_id IS NULL AND p_event_type = 'modified' THEN
      -- A 'modified' event with NO existing reservation to modify (V3
      -- changelog point 5) — never silently treated as a new booking.
      v_stage := 'modification_no_reservation_mark';  -- V9: diagnostic only
      UPDATE public.email_ingestions
         SET processing_status = 'needs_review',
             error_reason = 'modification event with no existing reservation for this source_id/external_booking_id',
             processed_at = NOW()
       WHERE id = v_ingestion_id;
      RETURN jsonb_build_object(
        'result', 'manual_review_required',
        'ingestion_id', v_ingestion_id,
        'reason', 'modification event with no existing reservation'
      );

    ELSIF v_reservation_id IS NULL AND p_event_type = 'new_booking' THEN
      -- V7: passenger-completeness guard — checked BEFORE any
      -- customer/reservation/guest/activity write, and strictly BEFORE
      -- a reservation number is ever allocated (see V7 changelog point
      -- 11). v_expected_passenger_count/v_usable_passenger_count were
      -- already computed once in Step 2b above.
      v_stage := 'passenger_completeness_check';  -- V9: diagnostic only
      IF v_usable_passenger_count <> v_expected_passenger_count THEN
        UPDATE public.email_ingestions
           SET processing_status = 'needs_review',
               error_reason = format(
                 'passenger count mismatch on create: expected %s usable passenger(s) (pax_adult=%s + pax_child=%s), found %s usable entr%s in p_passengers',
                 v_expected_passenger_count, p_pax_adult, COALESCE(p_pax_child, 0), v_usable_passenger_count,
                 CASE WHEN v_usable_passenger_count = 1 THEN 'y' ELSE 'ies' END
               ),
               processed_at = NOW()
         WHERE id = v_ingestion_id;
        RETURN jsonb_build_object(
          'result', 'manual_review_required',
          'ingestion_id', v_ingestion_id,
          'reason', 'passenger count mismatch',
          'expected_passenger_count', v_expected_passenger_count,
          'usable_passenger_count', v_usable_passenger_count
        );
      END IF;

      -- CREATE path. Customer resolution/creation happens ONLY here
      -- (V3 changelog point 4) — the update branch below never reaches
      -- this code. Never reached above this line — passenger
      -- completeness is validated before any customer/reservation write.
      v_stage := 'customer_resolution';  -- V9: diagnostic only
      IF p_customer_id IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM public.customers WHERE id = p_customer_id) THEN
          RAISE EXCEPTION 'ingest_civitatis_booking: provided customer_id % does not exist', p_customer_id;
        END IF;
        v_customer_id := p_customer_id;
      ELSE
        IF p_customer_full_name IS NULL OR btrim(p_customer_full_name) = '' THEN
          UPDATE public.email_ingestions
             SET processing_status = 'needs_review',
                 error_reason = 'no resolved customer_id and no booking-contact full name to create one',
                 processed_at = NOW()
           WHERE id = v_ingestion_id;
          RETURN jsonb_build_object(
            'result', 'manual_review_required',
            'ingestion_id', v_ingestion_id,
            'reason', 'missing booking-contact identity'
          );
        END IF;
        -- Booking-contact data only — never a passenger. Never invented:
        -- email/phone/nationality/country stay NULL when Civitatis did
        -- not provide them. import_type has no CHECK constraint
        -- restricting its values, so 'civitatis' needs no migration.
        v_stage := 'customer_insert';  -- V9: diagnostic only
        INSERT INTO public.customers (full_name, email, phone, source_id, import_type)
        VALUES (p_customer_full_name, p_customer_email, p_customer_phone, p_source_id, 'civitatis')
        RETURNING id INTO v_customer_id;
      END IF;

      v_stage := 'tour_lookup';  -- V9: diagnostic only
      SELECT name INTO v_tour_name FROM public.tours WHERE id = p_tour_id;
      v_stage := 'reference_number_allocation';  -- V9: diagnostic only
      SELECT public.next_ref_number('R', 'reservations', 'reservation_number') INTO v_reservation_number;

      v_stage := 'reservation_insert';  -- V9: diagnostic only
      INSERT INTO public.reservations (
        reservation_number, customer_id, tour_id, source_id, external_booking_id,
        status, payment_status, destination, check_in, check_out, check_in_time,
        pax_adult, pax_child, tour_language, total_amount, currency,
        retail_amount, retail_currency
      ) VALUES (
        v_reservation_number, v_customer_id, p_tour_id, p_source_id, p_external_booking_id,
        'pending_confirmation', 'pending', v_tour_name,
        p_check_in, p_check_in,  -- day-tour: check_out mirrors check_in (see schema audit)
        p_check_in_time,
        p_pax_adult, COALESCE(p_pax_child, 0),  -- pax_adult already validated NOT NULL/>0 in Step 2; pax_child's 0-default is the established parser contract, not a fabrication (see header)
        p_tour_language, p_total_amount, p_currency,
        p_retail_amount, p_retail_currency
      )
      RETURNING id INTO v_reservation_id;

      v_result := 'created';

      -- Passenger insert. The guard above already guarantees exactly
      -- expected_passenger_count usable entries exist, so this SELECT is
      -- guaranteed non-empty. sortOrder is cast defensively (V7): a
      -- malformed (non-numeric) or missing sortOrder value safely
      -- defaults to 0 instead of raising a cast exception that would
      -- abort this otherwise-valid call — see V7 changelog point 11.
      -- fullName is stored exactly as supplied — never trimmed here;
      -- btrim() is used only to decide usability above.
      v_stage := 'passenger_insert';  -- V9: diagnostic only
      INSERT INTO public.reservation_guests (reservation_id, full_name, sort_order)
      SELECT v_reservation_id, (g->>'fullName'),
             CASE WHEN g->>'sortOrder' ~ '^-?\d+$' THEN (g->>'sortOrder')::int ELSE 0 END
        FROM jsonb_array_elements(COALESCE(p_passengers, '[]'::jsonb)) AS g
       WHERE btrim(g->>'fullName') IS NOT NULL AND btrim(g->>'fullName') <> '';
      v_passengers_replaced := TRUE;

      v_stage := 'ingestion_mark_processed';  -- V9: diagnostic only
      UPDATE public.email_ingestions
         SET processing_status = 'processed', reservation_id = v_reservation_id, processed_at = NOW()
       WHERE id = v_ingestion_id;

      -- Exactly-once "new reservation" activity notification — only ever
      -- reached from this CREATE branch, which — by the UNIQUE
      -- constraint + advisory lock — can execute at most once per
      -- (source_id, external_booking_id), ever.
      v_stage := 'activity_log_insert';  -- V9: diagnostic only
      INSERT INTO public.activity_logs (entity_type, entity_id, action, description, metadata, performed_by)
      VALUES (
        'reservation', v_reservation_id, 'created',
        'Yeni Rezervasyon Geldi: ' || v_reservation_number,
        jsonb_build_object(
          'auto_ingested', true,
          'source', 'civitatis',
          'external_booking_id', p_external_booking_id
        ),
        NULL  -- no staff session performed this — the RLS policy this
              -- satisfies explicitly keys on performed_by IS NULL
      );

    ELSIF v_reservation_id IS NOT NULL AND p_event_type = 'modified' AND v_newer_exists THEN
      -- STALE modification for an existing reservation: zero side
      -- effects beyond this event's own audit row (V3 changelog points
      -- 1 and 6). No customer, reservation, guest, or activity write of
      -- any kind.
      v_stage := 'stale_mark_processed';  -- V9: diagnostic only
      UPDATE public.email_ingestions
         SET processing_status = 'processed', reservation_id = v_reservation_id, processed_at = NOW()
       WHERE id = v_ingestion_id;
      RETURN jsonb_build_object(
        'result', 'stale_ignored',
        'ingestion_id', v_ingestion_id,
        'reservation_id', v_reservation_id,
        'customer_id', v_customer_id
      );

    ELSIF v_reservation_id IS NOT NULL AND p_event_type = 'modified' AND NOT v_newer_exists THEN
      -- UPDATE path: the ONLY branch that ever writes reservation
      -- fields — reachable ONLY when p_event_type = 'modified' AND an
      -- existing reservation was found AND the event is not stale, all
      -- three required together (V4 changelog point 8).
      -- Customer identity is NEVER touched here (V3 changelog point 4):
      -- v_customer_id already holds the EXISTING reservation's
      -- customer_id from Step 4's lookup, read-only, for the return
      -- payload — no customers table write of any kind on this path,
      -- regardless of what p_customer_id/p_customer_full_name/
      -- p_customer_email/p_customer_phone were given.
      v_stage := 'reservation_update';  -- V9: diagnostic only
      UPDATE public.reservations SET
        check_in         = p_check_in,
        check_out        = p_check_in,
        check_in_time     = p_check_in_time,
        pax_adult          = p_pax_adult,
        pax_child           = COALESCE(p_pax_child, 0),
        tour_language        = p_tour_language,
        total_amount          = p_total_amount,
        currency                = p_currency,
        retail_amount            = p_retail_amount,
        retail_currency            = p_retail_currency
      WHERE id = v_reservation_id;
      -- Deliberately absent from this SET list (never written on an
      -- update, by construction — not merely by convention): customer_id,
      -- guide_id, guide_name, internal_notes, notes, status,
      -- payment_status, deposit_amount, pickup_location, pickup_time,
      -- vehicle_info, driver_name, hotel_name, hotel_confirmation,
      -- assigned_to, lead_id, quote_id, confirmed_at, completed_at,
      -- cancelled_at, cancel_reason, destination.

      v_result := 'updated';

      -- V7: passenger-list replacement now requires a COMPLETE match
      -- (usable_passenger_count = expected_passenger_count, both
      -- already computed once in Step 2b above), not merely "at least
      -- one usable entry" (V6/V3). An empty, partial, or otherwise
      -- incomplete passenger payload NEVER erases or partially
      -- overwrites a real, previously-recorded passenger list — see V7
      -- changelog point 11. The other independently-valid Civitatis-
      -- controlled reservation fields above are still applied
      -- regardless; only reservation_guests is protected here.
      IF v_usable_passenger_count = v_expected_passenger_count AND v_expected_passenger_count > 0 THEN
        v_stage := 'modification_passenger_replace';  -- V9: diagnostic only
        DELETE FROM public.reservation_guests WHERE reservation_id = v_reservation_id;
        -- sortOrder hardened exactly as the CREATE path (V7 changelog
        -- point 11); fullName stored exactly as supplied, never trimmed.
        INSERT INTO public.reservation_guests (reservation_id, full_name, sort_order)
        SELECT v_reservation_id, (g->>'fullName'),
               CASE WHEN g->>'sortOrder' ~ '^-?\d+$' THEN (g->>'sortOrder')::int ELSE 0 END
          FROM jsonb_array_elements(p_passengers) AS g
         WHERE btrim(g->>'fullName') IS NOT NULL AND btrim(g->>'fullName') <> '';
        v_passengers_replaced := TRUE;
      END IF;
      -- else: v_passengers_replaced stays FALSE; existing
      -- reservation_guests rows for this reservation are left completely
      -- untouched — covers empty, partial, and over-complete payloads
      -- alike (V7 widens V6's empty-only guard to any incomplete count).

      -- No activity_logs row on the update path — a modification never
      -- creates a second "new reservation" notification.
      v_stage := 'ingestion_mark_processed';  -- V9: diagnostic only
      UPDATE public.email_ingestions
         SET processing_status = 'processed', reservation_id = v_reservation_id, processed_at = NOW()
       WHERE id = v_ingestion_id;

    ELSE
      -- Defensively unreachable: Step 2 already guarantees p_event_type
      -- is exactly 'new_booking' or 'modified', and the five branches
      -- above are an exhaustive case split over
      -- {new_booking,modified} x {reservation exists?} x {stale?
      -- — only meaningful for modified+exists}. Never silently write
      -- business state if this is somehow reached anyway.
      v_stage := 'unexpected_branch';  -- V9: diagnostic only
      UPDATE public.email_ingestions
         SET processing_status = 'needs_review',
             error_reason = 'unexpected event_type/reservation-state combination',
             processed_at = NOW()
       WHERE id = v_ingestion_id;
      RETURN jsonb_build_object(
        'result', 'manual_review_required',
        'ingestion_id', v_ingestion_id,
        'reason', 'unexpected event_type/reservation-state combination'
      );
    END IF;

    RETURN jsonb_build_object(
      'result', v_result,
      'ingestion_id', v_ingestion_id,
      'reservation_id', v_reservation_id,
      'customer_id', v_customer_id,
      'passengers_replaced', v_passengers_replaced
    );

  EXCEPTION WHEN OTHERS THEN
    -- Rolls back to the implicit savepoint at the start of this BEGIN
    -- block — every customer/reservation/guest/activity write attempted
    -- above is undone together. The email_ingestions row from Step 1
    -- survives (it was written before this block began) and is now
    -- updated to a permanent, honest 'failed' record rather than being
    -- silently lost.
    v_error_text := SQLERRM;

    -- V9: diagnostic-only capture. GET STACKED DIAGNOSTICS reads
    -- information Postgres already computed for the exception that was
    -- just caught — none of these seven items can ever contain
    -- application data (no email body, no customer/passenger PII): they
    -- describe SQL error metadata only — a SQLSTATE code, the
    -- constraint/table/column the engine associated with the error (if
    -- any — empty string when not applicable, never an error to ask
    -- for), and PL/pgSQL's own internal function/line call-stack text.
    -- This is the ONLY new statement this migration adds to the
    -- EXCEPTION handler; it cannot itself raise.
    GET STACKED DIAGNOSTICS
      v_diag_sqlstate  = RETURNED_SQLSTATE,
      v_diag_constraint = CONSTRAINT_NAME,
      v_diag_table      = TABLE_NAME,
      v_diag_column     = COLUMN_NAME,
      v_diag_detail     = PG_EXCEPTION_DETAIL,
      v_diag_hint       = PG_EXCEPTION_HINT,
      v_diag_context    = PG_EXCEPTION_CONTEXT;

    -- error_reason keeps the ORIGINAL SQLERRM verbatim (never replaced
    -- or summarized) and gains the diagnostic stage plus the compact
    -- identifier-shaped diagnostics fields, in the exact
    -- "stage=<stage>; error=<original SQLERRM>" format requested, plus
    -- sqlstate/constraint/table/column/detail/hint. PG_EXCEPTION_CONTEXT
    -- (the one multi-line, potentially long field of the seven) is
    -- deliberately NOT appended here — it goes into the returned JSONB
    -- only (bounded to 1000 characters), to keep this audit column
    -- short and easy to scan.
    v_error_text := format(
      'stage=%s; error=%s; sqlstate=%s; constraint=%s; table=%s; column=%s; detail=%s; hint=%s',
      COALESCE(v_stage, 'unknown'),
      v_error_text,
      COALESCE(v_diag_sqlstate, '-'),
      COALESCE(NULLIF(v_diag_constraint, ''), '-'),
      COALESCE(NULLIF(v_diag_table, ''), '-'),
      COALESCE(NULLIF(v_diag_column, ''), '-'),
      COALESCE(NULLIF(v_diag_detail, ''), '-'),
      COALESCE(NULLIF(v_diag_hint, ''), '-')
    );

    UPDATE public.email_ingestions
       SET processing_status = 'failed',
           error_reason = v_error_text,
           processed_at = NOW()
     WHERE id = v_ingestion_id;

    RETURN jsonb_build_object(
      'result', 'failed',
      'ingestion_id', v_ingestion_id,
      'error', v_error_text,
      'stage', COALESCE(v_stage, 'unknown'),  -- V9: diagnostic only
      'diagnostics', jsonb_build_object(      -- V9: diagnostic only
        'sqlstate', v_diag_sqlstate,
        'constraint_name', NULLIF(v_diag_constraint, ''),
        'table_name', NULLIF(v_diag_table, ''),
        'column_name', NULLIF(v_diag_column, ''),
        'detail', NULLIF(v_diag_detail, ''),
        'hint', NULLIF(v_diag_hint, ''),
        'context', LEFT(COALESCE(v_diag_context, ''), 1000)
      )
    );
  END;
END;
$$;



COMMENT ON FUNCTION public.ingest_civitatis_booking IS
  'Atomically ingests one already-parsed, already-matched Civitatis '
  'booking-notification email. On the CREATE path (event_type= '
  'new_booking, no existing reservation): resolves/creates the '
  'booking-contact customer, creates the reservation, inserts '
  'passengers, records the email_ingestions audit row, and inserts '
  'exactly one activity_logs notification. On the UPDATE path '
  '(event_type=modified, an existing reservation found, event not '
  'stale — ALL THREE required together): updates ONLY the '
  'Civitatis-allowed reservation fields and, ONLY when the passenger '
  'payload''s usable count exactly equals pax_adult+pax_child, replaces '
  'reservation_guests (V7) — an empty, partial, or otherwise incomplete '
  'payload leaves the existing passenger list completely untouched '
  'while still applying every other valid field. CREATE itself refuses '
  'to write ANY business state (V7) unless the usable passenger count '
  'exactly equals pax_adult+pax_child, checked before a customer is '
  'resolved or a reservation number is allocated. Never touches customer '
  'identity on the UPDATE path, never creates a second activity row. A '
  'stale modification, '
  'a modification with no existing reservation, a second new_booking '
  'event for an already-existing reservation, or a call missing any '
  'required field has ZERO business-state side effects and is reported '
  'distinctly (stale_ignored / manual_review_required / '
  'booking_already_exists). Any unexpected error rolls back all '
  'business writes for that call while still recording a '
  '''failed'' audit row on the SAME email_ingestions row/id. '
  'Re-invoking with a gmail_message_id whose prior attempt is '
  '''processed'', ''received'', or ''needs_review'' is always a no-op '
  '(already_processed); ''needs_review'' is intentionally never '
  'auto-retried. Re-invoking one whose prior attempt is ''failed'' '
  'atomically reclaims that SAME row (failed -> received) via a single '
  'conditional UPSERT and reprocesses it as a fresh attempt. A '
  'non-blocking, gmail_message_id-scoped advisory lock, held for the '
  'whole call, guarantees at most one concurrent caller can ever claim '
  'or retry a given Gmail message at a time — a second, concurrent '
  'caller returns already_processed immediately rather than waiting and '
  're-deciding against the first caller''s eventual outcome (V6; fixes a '
  'concurrency gap an external review found in V5 before it was ever '
  'applied). A malformed or missing passenger sortOrder value safely '
  'defaults to 0 instead of aborting an otherwise-valid call (V7). '
  'A non-NULL p_passengers that is not a JSONB array (e.g. a '
  'double-encoded JSON string) is rejected pre-flight as a required- '
  'field problem (manual_review_required) instead of raising an '
  'unhandled jsonb_array_elements exception (V8). '
  'On an unexpected error, the failed email_ingestions row''s '
  'error_reason and the returned JSON both now also record which '
  'internal processing stage was last entered and Postgres''s own '
  'GET STACKED DIAGNOSTICS fields (sqlstate/constraint/table/column/ '
  'detail/hint/a bounded context) for that exact exception, purely for '
  'diagnosis — no business behavior changes (V9). '
  'SECURITY DEFINER; callable only by service_role — see this '
  'migration file''s header for the full contract. Never call directly '
  'from browser code.';


-- ──────────────────────────────────────────────────────────────────────────
-- SECURITY: restrict EXECUTE to service_role only — V9's original
-- 23-parameter REVOKE/GRANT, restored verbatim.
-- ──────────────────────────────────────────────────────────────────────────

REVOKE ALL ON FUNCTION public.ingest_civitatis_booking(
  TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TEXT, UUID, TEXT, DATE, TIME,
  INTEGER, INTEGER, NUMERIC, TEXT, NUMERIC, TEXT, UUID, TEXT, TEXT, TEXT, JSONB
) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.ingest_civitatis_booking(
  TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TEXT, UUID, TEXT, DATE, TIME,
  INTEGER, INTEGER, NUMERIC, TEXT, NUMERIC, TEXT, UUID, TEXT, TEXT, TEXT, JSONB
) FROM anon;

REVOKE ALL ON FUNCTION public.ingest_civitatis_booking(
  TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TEXT, UUID, TEXT, DATE, TIME,
  INTEGER, INTEGER, NUMERIC, TEXT, NUMERIC, TEXT, UUID, TEXT, TEXT, TEXT, JSONB
) FROM authenticated;

GRANT EXECUTE ON FUNCTION public.ingest_civitatis_booking(
  TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TEXT, UUID, TEXT, DATE, TIME,
  INTEGER, INTEGER, NUMERIC, TEXT, NUMERIC, TEXT, UUID, TEXT, TEXT, TEXT, JSONB
) TO service_role;

COMMIT;

-- ── END OF ROLLBACK ─────────────────────────────────────────────────────────
